
{'date': 'Sat May 26 2018 09:21:44.431 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 24
  self._esconde
  ^
IndentationError: expected an indented block
'''},
{'date': 'Sat May 26 2018 13:07:41.116 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 52
  self.t.append('{}µ{}'.format(char,str(window.Date.now())[-5:])
                                                                   ^
SyntaxError: invalid syntax
'''},
{'date': 'Sat May 26 2018 13:08:10.91 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 52
  self.t.append('{}µ{}'.format(char,str(window.Date().now())[-5:])
                                                                     ^
SyntaxError: invalid syntax
'''},
{'date': 'Sat May 26 2018 13:09:29.605 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 59
  self.texto = Texto(cena=self.cena, tit="diga,", txt='com q paus a canoa?',
                                                                                                                                                                                  ^
SyntaxError: invalid syntax
'''},
{'date': 'Sat May 26 2018 13:11:12.858 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 59
  self.texto = Texto(cena=self.cena, tit="diga,", txt='com q paus a canoa?',
                                                                                                                                                                                  ^
SyntaxError: invalid syntax
'''},
{'date': 'Sat May 26 2018 13:15:01.692 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 188
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 360
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 332
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 349
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 70
    Game()
  module <module> line 60
    texto=str("\n".join(self.texto.sai()))
AttributeError: 'Game' object has no attribute 'texto'
'''},
{'date': 'Sat May 26 2018 13:19:18.924 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 188
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 360
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 332
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 349
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 69
    Game()
  module <module> line 64
    self.texto.vai()
  module <module> line 39
    self.cena.elt <= Popup.POP.popup
NameError: name 'Popup' is not defined
'''},
{'date': 'Sat May 26 2018 13:19:39.933 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 188
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 360
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 332
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 349
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 69
    Game()
  module <module> line 64
    self.texto.vai()
  module <module> line 39
    self.cena.elt <= Popup.POP.popup
NameError: name 'Popup' is not defined
'''},
{'date': 'Sat May 26 2018 13:19:40.920 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 188
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 360
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 332
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 349
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 69
    Game()
  module <module> line 64
    self.texto.vai()
  module <module> line 39
    self.cena.elt <= Popup.POP.popup
NameError: name 'Popup' is not defined
'''},
{'date': 'Sat May 26 2018 13:24:02.322 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 188
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 360
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 332
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 349
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 69
    Game()
  module <module> line 64
    self.texto.vai()
  module <module> line 39
    self.cena.elt <= Popup.POP.popup
NameError: name 'Popup' is not defined
'''},
{'date': 'Sat May 26 2018 13:25:21.795 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 188
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 360
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 332
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 349
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 69
    Game()
  module <module> line 64
    self.texto.vai()
  module <module> line 39
    self.cena.elt <= Popup.POP.popup
NameError: name 'Popup' is not defined
'''},
{'date': 'Sat May 26 2018 13:29:23.664 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 188
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 360
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 332
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 349
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 69
    Game()
  module <module> line 64
    self.texto.vai()
  module <module> line 39
    self.cena.elt <= Popup.POP.popup
NameError: name 'Popup' is not defined
'''},
{'date': 'Sat May 26 2018 14:35:25.744 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 61
  foi=lambda *_:Texto(cena=self.cena, tit="score,", txt="\n".join(self.texto.sai())).vai())
                                                                                          ^
SyntaxError: invalid syntax
'''},
{'date': 'Sat May 26 2018 14:39:30.436 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 52
  return self.area.value if self.area else '', j.join(self.t)
                                              ^
SyntaxError: invalid syntax
'''},
{'date': 'Sat May 26 2018 14:42:50.774 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 66
  self.texto = Texto(cena=self.cena, tit="diga, com q paus a canoa?", texto= ""
                                                                                         ^
SyntaxError: invalid syntax
'''},
{'date': 'Sat May 26 2018 19:07:29.566 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 141
    Plotter(doc["pydiv"]).plot(x , y)
  module <module> line 69
    [self.graph(_x, _y) for _x, _y in zip(x, y)]
  module <module> line 63
    cur, prev = self.dataset[-1:-2]
ValueError: need more than 0 value to unpack
'''},
{'date': 'Sat May 26 2018 19:08:38.463 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 141
    Plotter(doc["pydiv"]).plot(x , y)
  module <module> line 69
    [self.graph(_x, _y) for _x, _y in zip(x, y)]
  module <module> line 63
    cur, prev = self.dataset[-2:-1]
ValueError: need more than 1 value to unpack
'''},
{'date': 'Sun May 27 2018 10:18:12.561 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 158
    Plotter(doc["pydiv"], "imaginário").plot(x, y)
  module <module> line 85
    self.display(self.pack(self.dataset)) if DEBUG else False
NameError: name 'DEBUG' is not defined
'''},
{'date': 'Sun May 27 2018 10:18:27.353 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 158
    Plotter(doc["pydiv"], "imaginário").plot(x, y)
  module <module> line 85
    self.display(self.pack(self.dataset)) if DEBUG else False
NameError: name 'DEBUG' is not defined
'''},
{'date': 'Sun May 27 2018 11:20:07.149 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 175
    Game()
  module <module> line 154
    self.pontua(self.texto.sai())
  module <module> line 159
    grafo_ = Plotter.unpack(pontos)
  module <module> line 83
    return [pair.split(MU) for pair in datapack.split(PR)]
AttributeError: 'tuple' object has no attribute 'split'
'''},
{'date': 'Sun May 27 2018 11:23:31.321 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 175
    Game()
  module <module> line 154
    self.pontua(self.texto.sai())
  module <module> line 160
    grafo = [int(t[2:6]) for _, t in grafo_]
ValueError: need more than 1 value to unpack
'''},
{'date': 'Sun May 27 2018 11:30:41.644 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 177
    Game()
  module <module> line 154
    self.pontua(self.texto.sai())
  module <module> line 159
    grafo_ = Plotter.unpack(pontos)
  module <module> line 83
    return [pair.split(MU) for pair in datapack.split(PR)]
AttributeError: 'tuple' object has no attribute 'split'
'''},
{'date': 'Sun May 27 2018 11:31:20.536 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 177
    Game()
  module <module> line 154
    self.pontua(self.texto.sai())
  module <module> line 159
    grafo_ = Plotter.unpack(pontos)
  module <module> line 83
    return [pair.split(MU) for pair in datapack.split(PR)]
AttributeError: 'tuple' object has no attribute 'split'
'''},
{'date': 'Sun May 27 2018 11:34:02.679 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 176
    Game()
  module <module> line 154
    self.pontua(self.texto.sai())
  module <module> line 159
    grafo_ = Plotter.unpack(pontos)
  module <module> line 83
    return [pair.split(MU) for pair in datapack.split(PR)]
AttributeError: 'tuple' object has no attribute 'split'
'''},
{'date': 'Sun May 27 2018 11:36:54.979 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 176
    Game()
  module <module> line 154
    self.pontua(self.texto.sai())
  module <module> line 159
    grafo_ = Plotter.unpack(pontos)
  module <module> line 83
    return [pair.split(MU) for pair in datapack.split(PR)]
AttributeError: 'tuple' object has no attribute 'split'
'''},