
{'date': 'Wed Oct 02 2019 13:53:26.895 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 24
  def vai_CenaRecepcao():
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Oct 04 2019 12:01:28.554 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 24
  def vai_CenaRecepcao():
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Oct 04 2019 12:02:39.962 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 26
    vai_CenaRecepcao()
NameError: name 'vai_CenaRecepcao' is not defined
'''},
{'date': 'Sun Sep 27 2020 12:22:15.64 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 24
  def vai_CenaRecepcao():
  ^
IndentationError: unexpected indent
'''},
{'date': 'Fri Dec 04 2020 14:25:14.941 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 24
  def vai_CenaRecepcao():
  ^
IndentationError: unexpected indent
'''},